- shell:
  - rm -rf ~/.config/fish
  - mkdir -p ~/.config/fish
  - curl -Lo .config/fish/functions/fisher.fish --create-dirs https://git.io/fisher

- link:
    ~/.config/fish/functions: .config/fish/functions
    ~/.config/fish/conf.d: .config/fish/conf.d
