- shell:
  - mkdir -p ~/.config/fish
  - rm -rf ~/.config/fish/*

- link:
    ~/.config/fish/fishd.archlinux: .config/fish/fishd.archlinux
    ~/.config/fish/config.fish: .config/fish/config.fish
    ~/.config/fish/functions: .config/fish/functions
