- shell:
    - mkdir -p ~/.config/nvim
    - curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- link:
    ~/.config/nvim/init.vim: .config/nvim/init.vim


- shell:
    - command: nvim +PlugInstall +qall
      description: "Installing nvim plugins..."
      stdin: true
      stdout: true
      stderr: true
