- shell:
    - mkdir -p ~/.config/nvim
    - curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    - mkdir -p ~/.config/fish/includes

- link:
    ~/.config/nvim/init.vim: .config/nvim/init.vim
    ~/.bashrc.d/aliases.d/nvim.bash: .bashrc.d/aliases.d/nvim.bash
    ~/.config/fish/includes/nvim.fish: .config/fish/includes/nvim.fish


- shell:
    - command: nvim +PlugInstall +qall
      description: "Installing nvim plugins..."
      stdin: true
      stdout: true
      stderr: true
