- shell:
    - mkdir -p ~/.tmux/plugins

- link:
    ~/.tmux.conf: .tmux.conf
    ~/.tmux/plugins/tpm: tpm

- shell:
    - ~/.tmux/plugins/tpm/bin/clean_plugins
    - ~/.tmux/plugins/tpm/bin/install_plugins
    - ~/.tmux/plugins/tpm/bin/update_plugins all
