- shell:
    - mkdir -p ~/.vim/backup ~/.vim/tmp ~/.vim/autoload ~/.vim/plug

- link:
    ~/.vimrc: .vimrc
    ~/.vim/autoload/plug.vim: vim-plug/plug.vim

- shell:
    - command: vim +PlugInstall +qall
      description: "Installing vim plugins..."
      stdin: true
      stdout: true
      stderr: true
