- defaults:
    link:
      create: true
      relink: true

- shell:
    -
      command: "git submodule update --init --recursive"
      description: "Installing submodules"
    - mkdir -p ~/.bashrc.d
    - mkdir -p ~/.bashrc.d/aliases.d

- link:
    ~/.bashrc: .bashrc
    ~/.bash_profile: .bash_profile
    ~/.bashrc.d/aliases.bash: .bashrc.d/aliases.bash
    ~/.bashrc.d/aliases.d/base.bash: .bashrc.d/aliases.d/base.bash
    ~/.bashrc.d/base.bash: .bashrc.d/base.bash
    ~/.bashrc.d/editor.bash: .bashrc.d/editor.bash
    ~/.bashrc.d/history.bash: .bashrc.d/history.bash
    ~/.bashrc.d/ps1.bash: .bashrc.d/ps1.bash

- clean: ['~']
