- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- shell:
    -
      command: "git submodule update --init --recursive"
      description: "Installing submodules"
- link:
    ~/.ssh/config: .ssh/config
    ~/.bin: .bin
