- defaults:
    link:
      create: true
      relink: true

- clean: ['~']
- clean: ['~/bashrc.d']
- clean: ['~/bashrc.d/aliases.d']

- shell:
    -
      command: "git submodule update --init --recursive"
      description: "Installing submodules"
    - mkdir -p ~/.bashrc.d
    - mkdir -p ~/.bashrc.d/aliases.d
    - mkdir -p ~/.ssh

- link:
    ~/.bashrc: .bashrc
    ~/.bash_profile: .bash_profile
    ~/.bashrc.d/aliases.bash: .bashrc.d/aliases.bash
    ~/.bashrc.d/aliases.d/base.bash: .bashrc.d/aliases.d/base.bash
    ~/.bashrc.d/base.bash: .bashrc.d/base.bash
    ~/.bashrc.d/editor.bash: .bashrc.d/editor.bash
    ~/.bashrc.d/history.bash: .bashrc.d/history.bash
    ~/.bashrc.d/ps1.bash: .bashrc.d/ps1.bash
    ~/.ssh/config: .ssh/config
    ~/.bin: .bin
