#!/usr/bin/env python3
from i3pystatus import Status

S_base03  = "#002b36"
S_base02  = "#073642"
S_base01  = "#586e75"
S_base00  = "#657b83"
S_base0   = "#839496"
S_base1   = "#93a1a1"
S_base2   = "#eee8d5"
S_base3   = "#fdf6e3"
S_yellow  = "#b58900"
S_orange  = "#cb4b16"
S_red     = "#dc322f"
S_magenta = "#d33682"
S_violet  = "#6c71c4"
S_blue    = "#268bd2"
S_cyan    = "#2aa198"
S_green   = "#859900"

def separator(text):
  status.register("text",
                  text="<b>" + text + "</b>",
                  color=S_base00,
                  hints={"markup":"pango"})


status = Status()

status.register("ping",
                color=S_green)
separator("ping")
status.register("network",
                format_up="{interface} {network_graph} {kbs:>10}kb/s",
                start_color=S_green,
                end_color=S_red)
separator("net")
status.register("cpu_usage_graph",
                format="{cpu_graph} {usage:>3}%",
                start_color=S_green,
                end_color=S_red)
status.register("cpu_freq",
                format="{avgg}GHz",
                color=S_green)
separator("cpu")
status.register("mem",
                format="{percent_used_mem:>4}%",
                color=S_green,
                warn_color=S_yellow,
                alert_color=S_red)
status.register("mem_bar",
                format="{used_mem_bar}",
                color=S_green,
                warn_color=S_yellow,
                alert_color=S_red)
separator("ram")
status.register("uptime",
                format="{days}d {hours}h {mins}m {secs}s",
                color=S_green)
separator("uptime")
# status.register("disk", path="/", format="root {percentage_used:>4}%")
# status.register("disk", path="/tmp", format="tmp {percentage_used}%")
# status.register("disk", path="/usr/local/google/home/samwho", format="home {percentage_used}%")
# status.register("load", format="load {avg1:>4} {avg5:>4} {avg15:>4} {tasks:>4}")
status.register("pulseaudio")


status.run()
